// <auto-generated />
namespace HospitalProjectTeamThree.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class usertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usertable));
        
        string IMigrationMetadata.Id
        {
            get { return "202003281725415_usertable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
