// <auto-generated />
namespace HospitalProjectTeamThree.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class joblistingsupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(joblistingsupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "202004090219251_job listings updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
