// <auto-generated />
namespace HospitalProjectTeamThree.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class events_users_many_to_many_removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(events_users_many_to_many_removed));
        
        string IMigrationMetadata.Id
        {
            get { return "202004020148468_events_users_many_to_many_removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
