// <auto-generated />
namespace HospitalProjectTeamThree.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updatingdocotrstableandtopics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatingdocotrstableandtopics));
        
        string IMigrationMetadata.Id
        {
            get { return "202004021620280_updating docotrs table and topics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
