// <auto-generated />
namespace HospitalProjectTeamThree.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class droppingusersingetwellcardattempt2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(droppingusersingetwellcardattempt2));
        
        string IMigrationMetadata.Id
        {
            get { return "202004041812432_dropping users in get well card attempt 2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
