// <auto-generated />
namespace HospitalProjectTeamThree.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addingfirstnamelastnametouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingfirstnamelastnametouser));
        
        string IMigrationMetadata.Id
        {
            get { return "202004080035582_adding first name last name to user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
