// <auto-generated />
namespace HospitalProjectTeamThree.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class volunteerpositionvolunteersview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(volunteerpositionvolunteersview));
        
        string IMigrationMetadata.Id
        {
            get { return "202004120357574_volunteer position volunteers view"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
