// <auto-generated />
namespace HospitalProjectTeamThree.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addinguserIdingetwellsooncard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addinguserIdingetwellsooncard));
        
        string IMigrationMetadata.Id
        {
            get { return "202004032106431_adding userId in get well soon card"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
