// <auto-generated />
namespace HospitalProjectTeamThree.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class LiveWaitTimestableupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LiveWaitTimestableupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202004110134578_Live Wait Times table update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
